name: garden_plant
version: 0.0.1
author: Your Name
description: garden_plant application that uses dartling for its model.
homepage: http://ondart.me/
dependencies:
  angular: '>=0.9.2'
  angular_node_bind: any
  browser: any
  dartling:
    git: https://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: https://github.com/dzenanr/dartling_default_app.git
  polymer: any
transformers:
- polymer:
    entry_points: web/angularpolymer.html
